services:
  - type: web
    name: njuka-webapp-backend
    runtime: python
    region: oregon
    branch: dev
    rootDir: backend/njuka-webapp-backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
